from distutils.core import setup

setup(
    name='kpi',
    version='0.01',
    packages=['kpi', 'Lib.distutils', 'Lib.encodings', 'Lib.importlib', 'Lib.collections', 'Lib.site-packages.pip',
              'Lib.site-packages.pip.req', 'Lib.site-packages.pip.vcs', 'Lib.site-packages.pip.utils',
              'Lib.site-packages.pip.compat', 'Lib.site-packages.pip.models', 'Lib.site-packages.pip._vendor',
              'Lib.site-packages.pip._vendor.distlib', 'Lib.site-packages.pip._vendor.distlib._backport',
              'Lib.site-packages.pip._vendor.colorama', 'Lib.site-packages.pip._vendor.html5lib',
              'Lib.site-packages.pip._vendor.html5lib._trie', 'Lib.site-packages.pip._vendor.html5lib.filters',
              'Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'Lib.site-packages.pip._vendor.html5lib.treebuilders', 'Lib.site-packages.pip._vendor.lockfile',
              'Lib.site-packages.pip._vendor.progress', 'Lib.site-packages.pip._vendor.requests',
              'Lib.site-packages.pip._vendor.requests.packages',
              'Lib.site-packages.pip._vendor.requests.packages.chardet',
              'Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'Lib.site-packages.pip._vendor.packaging', 'Lib.site-packages.pip._vendor.cachecontrol',
              'Lib.site-packages.pip._vendor.cachecontrol.caches', 'Lib.site-packages.pip._vendor.webencodings',
              'Lib.site-packages.pip._vendor.pkg_resources', 'Lib.site-packages.pip.commands',
              'Lib.site-packages.pip.operations', 'Lib.site-packages.wheel', 'Lib.site-packages.wheel.tool',
              'Lib.site-packages.wheel.signatures', 'Lib.site-packages.setuptools',
              'Lib.site-packages.setuptools.extern', 'Lib.site-packages.setuptools.command',
              'Lib.site-packages.pkg_resources', 'Lib.site-packages.pkg_resources.extern',
              'Lib.site-packages.pkg_resources._vendor', 'Lib.site-packages.pkg_resources._vendor.packaging'],
    url='https://github.com/deshengio/kpi',
    license='MIT',
    author='Desheng',
    author_email='io.desheng@gmail.com',
    description='Just for prototype'
)
